components {
  id: "model_tiers"
  component: "/shadow_mapping/model_tiers.script"
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 20.0\n"
  "friction: 0.95\n"
  "restitution: 0.7\n"
  "group: \"gold\"\n"
  "mask: \"player\"\n"
  "mask: \"ground\"\n"
  "mask: \"ball\"\n"
  "mask: \"env\"\n"
  "mask: \"gold\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 0.1959175\n"
  "  data: 0.128296\n"
  "  data: 0.3538555\n"
  "}\n"
  "linear_damping: 0.9\n"
  "angular_damping: 0.7\n"
  ""
}
embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/assets/models/forest/sources/Gold_Bar.gltf\"\n"
  "skeleton: \"/assets/models/forest/sources/Grass_1_C_Color1.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"resource\"\n"
  "  material: \"/shadow_mapping/materials/high/diffuse.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/assets/models/forest/resource_texture.png\"\n"
  "  }\n"
  "}\n"
  ""
  position {
    y: -0.13
  }
}
