components {
  id: "model_tiers"
  component: "/shadow_mapping/model_tiers.script"
}
embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/assets/models/forest/sources/Wood_Log_B.gltf\"\n"
  "skeleton: \"/assets/models/forest/sources/Wood_Log_B.gltf\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"resource\"\n"
  "  material: \"/shadow_mapping/materials/high/diffuse.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/assets/models/forest/resource_texture.png\"\n"
  "  }\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"env\"\n"
  "mask: \"movable\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: 0.8\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 0.275\n"
  "  data: 1.191809\n"
  "  data: 0.675\n"
  "}\n"
  ""
}
